### ISSUE TITLE
[English support]: A PHP Error was encountered

### ISSUE THREAD

**Issue by wolone** [WoW-CMS/support#3] opened 2021-05-23 01:52 UTC
# Wow-CMS English support

### What operating system are you using?
- [x] Linux

### What version of PHP do you use?
- [x] PHP 7.2

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] VPS

### Which emulator are you using and which version?
- [x] AzerothCore

### Describe the bug
```
A PHP Error was encountered
Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 136

Backtrace:

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 282
Function: _ci_load_library

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 306
Function: library

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 247
Function: libraries

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 68
Function: initialize

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Base.php
Line: 65
Function: __construct

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Base.php
Line: 70
Function: __construct

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Controller.php
Line: 4
Function: require_once

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Modules.php
Line: 168
Function: include_once

File: /www/wwwroot/wow.2121567.com/application/modules/home/controllers/Home.php
Line: 38
Function: spl_autoload_call

File: /www/wwwroot/wow.2121567.com/index.php
Line: 320
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: session_start(): Failed to initialize storage module: user (path: )

Filename: Session/Session.php

Line Number: 143

Backtrace:

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 282
Function: _ci_load_library

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 306
Function: library

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 247
Function: libraries

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Loader.php
Line: 68
Function: initialize

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Base.php
Line: 65
Function: __construct

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Base.php
Line: 70
Function: __construct

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Controller.php
Line: 4
Function: require_once

File: /www/wwwroot/wow.2121567.com/application/third_party/MX/Modules.php
Line: 168
Function: include_once

File: /www/wwwroot/wow.2121567.com/application/modules/home/controllers/Home.php
Line: 38
Function: spl_autoload_call

File: /www/wwwroot/wow.2121567.com/index.php
Line: 320
Function: require_once
```

### How can I reproduce the problem?

wow.2121567.com

**Comment by pangolp** [comment] 2021-05-23 14:08
When I enter the web, I don't see that error, I get another one, like the database was not found.

**Comment by wolone** [comment] 2021-05-23 18:23
Please visit again and try again

**Comment by wolone** [comment] 2021-05-23 18:25
`$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;`
I remember that I was able to access it normally by modifying this section

**Comment by wolone** [comment] 2021-05-23 18:27
Why does the config.php file not correctly identify the database type after the installation is complete?

**Comment by wolone** [comment] 2021-05-23 18:28
`
$config['sess_driver'] = 'files';//Here I remember it should be database
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
`

**Comment by pangolp** [comment] 2021-05-24 14:04
> Why does the config.php file not correctly identify the database type after the installation is complete?

If the installation is interrupted at some point, either because of a missing apache2 module or a missing php extension, it may not complete the installation process correctly.

**Comment by pangolp** [comment] 2021-05-24 14:05
In the master version of the repository, the sections, for the moment, are still managed by files. It is strange, that by changing them to database, you have been able to solve the problem. Anyway, as the issue is solved, I'm going to close it. If you have any other problem, just reopen an issue.

**Closed by pangolp** 2021-05-24 14:05 UTC
